# List of evaluation scripts (baselines)
baselines:
  - rda_planner_diff.py
  - rda_traj_planner_diff.py
  - rda_dyna_search_planner_diff.py
  - sfm_planner_diff.py
  - dwa_planner_diff.py
  - dwa_improved_planner_diff.py

# Fixed paths
log_dir: logs/topography
config_dir: socialRPF/layout_scenarios/config

# Target path types
p_values:
  - back
  - left_side

n_trials: 100

# Scenario -> -m value
scenarios:
  ClutterOrcaObs10H30: 264
  ClutterOrcaObs20H30: 265
  ClutterOrcaObs40H30: 291

  ClutterOrcaObs30H10: 276
  ClutterOrcaObs30H20: 280
  ClutterOrcaObs30H30: 290
  ClutterOrcaObs30H40: 265
