world:
  height: 10.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 8, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [8.0, 6.3, 0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.0, 5.0, 0]
    goal: [38.5, 5.0, 0.0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }

obstacle:
  - shape: {name: rectangle, length: 40.0, width: 2.5}
    state: [20.0, 1.25, 0]
    color: darkgray
  - shape: {name: rectangle, length: 40.0, width: 2.5}
    state: [20.0, 8.75, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [6.24, 6.41, -0.046]
    goal:
      - [[6.24, 6.41, -0.046], [35.32, 4.6, -1.92]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.04, 5.0, 1.695]
    goal:
      - [[18.04, 5.0, 1.695], [21.95, 4.81, 1.972]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.62, 6.35, -0.97]
    goal:
      - [[12.62, 6.35, -0.97], [32.96, 6.31, 1.194]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.45, 3.71, -1.049]
    goal:
      - [[12.45, 3.71, -1.049], [36.6, 3.41, 1.214]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [4.53, 5.04, -2.041]
    goal:
      - [[4.53, 5.04, -2.041], [35.03, 5.24, 1.585]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.18, 6.05, 1.392]
    goal:
      - [[15.18, 6.05, 1.392], [29.42, 4.4, 0.716]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [5.76, 3.65, -2.489]
    goal:
      - [[5.76, 3.65, -2.489], [34.93, 5.13, -3.061]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [2.94, 4.51, -2.881]
    goal:
      - [[2.94, 4.51, -2.881], [35.67, 5.97, 0.125]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.47, 5.04, 2.555]
    goal:
      - [[11.47, 5.04, 2.555], [26.65, 5.82, 1.976]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [2.7, 6.01, -1.739]
    goal:
      - [[2.7, 6.01, -1.739], [26.52, 3.77, -0.193]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [9.8, 5.21, 0.959]
    goal:
      - [[9.8, 5.21, 0.959], [34.75, 6.09, -0.888]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [0.66, 5.53, -0.213]
    goal:
      - [[0.66, 5.53, -0.213], [31.49, 3.92, -1.908]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [35.56, 3.77, -0.276]
    goal:
      - [[35.56, 3.77, -0.276], [7.34, 4.2, 1.832]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [25.21, 6.04, -1.484]
    goal:
      - [[25.21, 6.04, -1.484], [7.89, 4.48, 0.614]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.64, 5.26, 0.802]
    goal:
      - [[22.64, 5.26, 0.802], [7.6, 3.96, 2.116]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [30.37, 6.36, 1.472]
    goal:
      - [[30.37, 6.36, 1.472], [17.27, 3.68, -0.375]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [28.55, 3.69, -2.319]
    goal:
      - [[28.55, 3.69, -2.319], [17.69, 3.55, -2.288]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [28.75, 6.1, 0.877]
    goal:
      - [[28.75, 6.1, 0.877], [16.57, 5.51, 0.012]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [26.59, 4.21, 2.189]
    goal:
      - [[26.59, 4.21, 2.189], [7.42, 4.91, 0.598]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.68, 3.69, -2.634]
    goal:
      - [[22.68, 3.69, -2.634], [7.51, 4.95, 0.79]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
