world:
  height: 20.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 12, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [15.096054341155472, 3.7, 1.5707963267948966]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.096054341155472, 5.0, 1.5707963267948966]
    goal: [29.46863056249093, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 18.45, width: 0.4}
    state: [9.225, 10.0, 0]
    color: darkgray
  - shape: {name: rectangle, length: 18.45, width: 0.4}
    state: [30.775, 10.0, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [25.54773241473736, 5.0, 1.5707963267948966]
    goal: [20.141706990372473, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.902702279982915, 5.0, 1.5707963267948966]
    goal: [12.956612566232115, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [31.94237779138352, 5.0, 1.5707963267948966]
    goal: [10.637881218995267, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [30.38473143779312, 5.0, 1.5707963267948966]
    goal: [15.184066017721552, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.109231298390988, 5.0, 1.5707963267948966]
    goal: [18.18704588718706, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [28.475789931174525, 5.0, 1.5707963267948966]
    goal: [21.74570602686869, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.634110374343715, 16.0, 1.5707963267948966]
    goal: [8.00537045416026, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [21.541523669656158, 16.0, 1.5707963267948966]
    goal: [18.52308822054462, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.224346338274017, 16.0, 1.5707963267948966]
    goal: [31.090351040627624, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.362900493421883, 16.0, 1.5707963267948966]
    goal: [23.803038176578447, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
