world:
  height: 20.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 12, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [13.032018112270485, 3.7, 1.5707963267948966]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.032018112270485, 5.0, 1.5707963267948966]
    goal: [23.57899801424054, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 18.6, width: 0.4}
    state: [9.3, 10.0, 0]
    color: darkgray
  - shape: {name: rectangle, length: 18.6, width: 0.4}
    state: [30.7, 10.0, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.123498906800734, 5.0, 1.5707963267948966]
    goal: [20.359610658647988, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [24.29019419849792, 5.0, 1.5707963267948966]
    goal: [31.6706755529532, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [25.895773685843174, 5.0, 1.5707963267948966]
    goal: [11.609195176828633, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [27.648997337519088, 5.0, 1.5707963267948966]
    goal: [18.616641927692314, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.686785994117793, 5.0, 1.5707963267948966]
    goal: [13.381709904452237, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.168333600220603, 5.0, 1.5707963267948966]
    goal: [28.4999627711737, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.206282067224745, 5.0, 1.5707963267948966]
    goal: [26.61475647836521, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [30.907614645323626, 5.0, 1.5707963267948966]
    goal: [8.7224926413257, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [30.5377819417896, 16.0, 1.5707963267948966]
    goal: [21.40192949090082, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.622690861740004, 16.0, 1.5707963267948966]
    goal: [27.873597510373255, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [27.28583849803718, 16.0, 1.5707963267948966]
    goal: [19.648004670185635, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [29.0259875215082, 16.0, 1.5707963267948966]
    goal: [8.929201041603147, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [9.619335616189183, 16.0, 1.5707963267948966]
    goal: [17.874047466187385, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.999947873106837, 16.0, 1.5707963267948966]
    goal: [25.41921076561514, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
