world:
  height: 20.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 12, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [30.769702161476022, 3.7, 1.5707963267948966]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [30.769702161476022, 5.0, 1.5707963267948966]
    goal: [29.235726052528328, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 18.75, width: 0.4}
    state: [9.375, 10.0, 0]
    color: darkgray
  - shape: {name: rectangle, length: 18.75, width: 0.4}
    state: [30.625, 10.0, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.901972901865584, 5.0, 1.5707963267948966]
    goal: [8.272324555647394, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.573575562799867, 5.0, 1.5707963267948966]
    goal: [12.12554847213358, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [9.834459807916476, 5.0, 1.5707963267948966]
    goal: [22.334338098374797, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.810725387002966, 5.0, 1.5707963267948966]
    goal: [24.537940780496147, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [23.74686229805858, 5.0, 1.5707963267948966]
    goal: [18.677598236426014, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [25.57663055440656, 5.0, 1.5707963267948966]
    goal: [14.382957036157281, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.519237015741083, 5.0, 1.5707963267948966]
    goal: [10.54738101140268, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [25.467324157367706, 16.0, 1.5707963267948966]
    goal: [9.407136763310403, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.938760112170105, 16.0, 1.5707963267948966]
    goal: [24.820386386293873, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.451848130585498, 16.0, 1.5707963267948966]
    goal: [13.033685719721657, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
