world:
  height: 20.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 12, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [31.314941415948983, 3.7, 1.5707963267948966]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [31.314941415948983, 5.0, 1.5707963267948966]
    goal: [25.923491278723205, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 18.75, width: 0.4}
    state: [9.375, 10.0, 0]
    color: darkgray
  - shape: {name: rectangle, length: 18.75, width: 0.4}
    state: [30.625, 10.0, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.428181756516096, 5.0, 1.5707963267948966]
    goal: [16.79314355841713, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.321622842360071, 5.0, 1.5707963267948966]
    goal: [13.42677544707163, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.442097562871243, 5.0, 1.5707963267948966]
    goal: [9.839848833457193, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.162636898315776, 5.0, 1.5707963267948966]
    goal: [15.239690849853382, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.470106969716117, 5.0, 1.5707963267948966]
    goal: [19.843311378655663, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [26.358085005069924, 5.0, 1.5707963267948966]
    goal: [21.87788439130697, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.142978893997602, 16.0, 1.5707963267948966]
    goal: [17.253098538688427, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [31.589563312969094, 16.0, 1.5707963267948966]
    goal: [19.73784143975533, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.05601956917064, 16.0, 1.5707963267948966]
    goal: [13.316320534697674, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.53212067723116, 16.0, 1.5707963267948966]
    goal: [11.400959314199163, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
