world:
  height: 20.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 12, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [12.83995230633926, 3.7, 1.5707963267948966]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.83995230633926, 5.0, 1.5707963267948966]
    goal: [9.668086946085838, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 18.6, width: 0.4}
    state: [9.3, 10.0, 0]
    color: darkgray
  - shape: {name: rectangle, length: 18.6, width: 0.4}
    state: [30.7, 10.0, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.644731016536742, 5.0, 1.5707963267948966]
    goal: [13.641311975558297, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.64884041235498, 5.0, 1.5707963267948966]
    goal: [18.12435443875275, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [24.56689793712502, 5.0, 1.5707963267948966]
    goal: [30.005532624637297, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [30.45281682114732, 5.0, 1.5707963267948966]
    goal: [23.701544314394468, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.555568633742794, 5.0, 1.5707963267948966]
    goal: [20.561037645500274, 16.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [30.004912432826064, 16.0, 1.5707963267948966]
    goal: [19.889522229353396, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.55896299288176, 16.0, 1.5707963267948966]
    goal: [27.003347120968634, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [27.689881731077257, 16.0, 1.5707963267948966]
    goal: [16.822545209507254, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.337870019729458, 16.0, 1.5707963267948966]
    goal: [21.449710168316273, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [24.01807529172151, 16.0, 1.5707963267948966]
    goal: [8.114237660125761, 5.0, 1.5707963267948966]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 1.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
        name: "orca",
        vxmax: 1.5,
        vymax: 1.5,
        acceler: 1.0,
        safe_dist: 0.4
      }
