world:
  height: 40.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [6.7, 20.0, 0.0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.0, 20.0, 0.0]
    goal: [38.5, 20.0, 0.0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [8.8, 31.2, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [8.8, 8.8, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [31.2, 8.8, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [31.2, 31.2, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.22, 32.73, -0.587]
    goal:
      - [[20.22, 32.73, -0.587], [20.81, 11.05, -0.546]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.51, 18.75, 2.116]
    goal:
      - [[11.51, 18.75, 2.116], [33.01, 21.01, 1.506]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.39, 35.26, -0.658]
    goal:
      - [[20.39, 35.26, -0.658], [19.46, 21.02, 3.108], [34.34, 20.37, -2.316]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.6, 31.31, 0.558]
    goal:
      - [[20.6, 31.31, 0.558], [21.01, 19.55, -2.122], [12.87, 21.19, 0.358]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.13, 29.66, -1.096]
    goal:
      - [[20.13, 29.66, -1.096], [19.97, 21.08, -2.085], [11.8, 20.93, -2.585]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.68, 26.91, 0.503]
    goal:
      - [[20.68, 26.91, 0.503], [18.86, 19.61, -1.338], [2.34, 19.99, 0.676]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.96, 37.5, -1.15]
    goal:
      - [[19.96, 37.5, -1.15], [19.39, 19.76, 1.525], [12.95, 20.15, 2.186]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.55, 8.01, 0.335]
    goal:
      - [[19.55, 8.01, 0.335], [20.73, 19.26, 0.223], [34.3, 20.42, -2.203]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.34, 9.23, -1.31]
    goal:
      - [[20.34, 9.23, -1.31], [20.55, 19.56, 0.93], [32.48, 19.05, -2.482]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.08, 2.5, 0.284]
    goal:
      - [[19.08, 2.5, 0.284], [19.02, 19.6, -3.052], [34.39, 19.52, 1.362]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [3.45, 19.86, 0.115]
    goal:
      - [[3.45, 19.86, 0.115], [20.07, 20.12, 0.142], [20.5, 10.65, -1.66]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [1.64, 19.15, 1.094]
    goal:
      - [[1.64, 19.15, 1.094], [20.05, 19.39, -2.038], [19.19, 5.5, 1.294]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.04, 20.7, 0.26]
    goal:
      - [[13.04, 20.7, 0.26], [19.35, 18.71, 2.51], [19.84, 13.88, 2.578]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [29.18, 19.51, 1.722]
    goal:
      - [[29.18, 19.51, 1.722], [20.85, 21.11, 1.229], [20.22, 33.93, 0.523]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [33.09, 20.8, -2.931]
    goal:
      - [[33.09, 20.8, -2.931], [21.13, 18.86, 1.448], [19.41, 10.87, 1.454]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [26.92, 20.77, 0.096]
    goal:
      - [[26.92, 20.77, 0.096], [20.62, 19.75, -0.507], [18.83, 11.02, -1.095]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [34.47, 20.56, 1.038]
    goal:
      - [[34.47, 20.56, 1.038], [18.95, 19.08, 1.709], [19.53, 11.88, -1.509]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [31.54, 18.95, 2.637]
    goal:
      - [[31.54, 18.95, 2.637], [19.71, 19.2, 3.066], [20.89, 13.32, -1.118]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
