world:
  height: 40.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [8.0, 21.3, 0.0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.0, 20.0, 0.0]
    goal: [38.5, 20.0, 0.0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 17.3, width: 17.3}
    state: [8.65, 31.35, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.3, width: 17.3}
    state: [8.65, 8.65, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.3, width: 17.3}
    state: [31.35, 8.65, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.3, width: 17.3}
    state: [31.35, 31.35, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [10.61, 20.61, 0.894]
    goal:
      - [[10.61, 20.61, 0.894], [36.8, 21.29, 1.905]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.99, 19.14, 0.588]
    goal:
      - [[11.99, 19.14, 0.588], [31.48, 19.05, 2.697]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [5.76, 18.77, 0.884]
    goal:
      - [[5.76, 18.77, 0.884], [30.38, 19.86, 1.099]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [35.05, 20.77, 2.553]
    goal:
      - [[35.05, 20.77, 2.553], [5.19, 20.97, -0.764]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [30.74, 19.02, 0.129]
    goal:
      - [[30.74, 19.02, 0.129], [1.18, 21.23, 0.423]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.81, 36.0, -0.848]
    goal:
      - [[18.81, 36.0, -0.848], [20.55, 18.34, 2.241], [2.36, 20.31, -0.686]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [21.18, 31.87, -2.723]
    goal:
      - [[21.18, 31.87, -2.723], [19.91, 19.28, 0.037], [5.67, 21.1, -2.121]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.4, 30.73, 1.425]
    goal:
      - [[20.4, 30.73, 1.425], [20.23, 18.35, -0.605], [4.58, 19.34, -0.963]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.43, 38.42, -2.214]
    goal:
      - [[19.43, 38.42, -2.214], [21.59, 21.06, 2.557], [5.0, 20.93, 0.349]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.79, 3.57, 0.184]
    goal:
      - [[18.79, 3.57, 0.184], [19.4, 19.92, -2.07], [31.65, 20.67, -0.297]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [21.39, 8.42, -1.635]
    goal:
      - [[21.39, 8.42, -1.635], [20.99, 18.8, -0.399], [27.38, 18.62, 2.848]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.54, 10.41, -2.695]
    goal:
      - [[19.54, 10.41, -2.695], [21.42, 20.92, -2.251], [28.85, 19.79, -0.782]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.3, 13.96, -0.939]
    goal:
      - [[19.3, 13.96, -0.939], [21.1, 21.08, 0.221], [0.77, 18.8, 1.713]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.11, 12.19, 0.859]
    goal:
      - [[20.11, 12.19, 0.859], [21.06, 19.92, 3.025], [5.35, 19.95, -0.093]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [2.03, 19.69, 0.326]
    goal:
      - [[2.03, 19.69, 0.326], [21.37, 19.92, 2.064], [19.52, 27.37, -1.577]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [26.24, 19.08, 1.576]
    goal:
      - [[26.24, 19.08, 1.576], [19.06, 18.43, -1.548], [18.88, 25.78, 1.815]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [37.17, 20.65, -2.066]
    goal:
      - [[37.17, 20.65, -2.066], [21.33, 18.87, 2.84], [19.31, 33.65, 1.516]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [26.04, 21.14, 0.0]
    goal:
      - [[26.04, 21.14, 0.0], [19.91, 20.18, -0.441], [18.54, 32.72, 2.42]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
