world:
  height: 40.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [8.0, 21.3, 0.0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.0, 20.0, 0.0]
    goal: [38.5, 20.0, 0.0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [8.8, 31.2, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [8.8, 8.8, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [31.2, 8.8, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [31.2, 31.2, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.81, 29.04, 2.437]
    goal:
      - [[18.81, 29.04, 2.437], [21.23, 13.08, 1.81]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.53, 8.12, 0.593]
    goal:
      - [[20.53, 8.12, 0.593], [20.37, 31.5, 1.443]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [32.8, 19.44, 0.759]
    goal:
      - [[32.8, 19.44, 0.759], [13.8, 20.21, 0.142]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [29.2, 21.04, -0.939]
    goal:
      - [[29.2, 21.04, -0.939], [3.47, 19.79, -0.068]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.85, 1.48, 1.418]
    goal:
      - [[18.85, 1.48, 1.418], [20.19, 18.99, -2.396], [28.12, 19.34, -0.688]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.39, 10.71, -2.028]
    goal:
      - [[19.39, 10.71, -2.028], [21.27, 20.42, 0.455], [2.01, 19.88, 2.465]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.75, 10.04, -3.091]
    goal:
      - [[20.75, 10.04, -3.091], [19.13, 18.89, -1.918], [5.52, 20.36, 1.007]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.74, 11.94, -0.191]
    goal:
      - [[19.74, 11.94, -0.191], [20.14, 20.86, 2.67], [2.8, 21.15, 0.123]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [4.14, 20.81, 0.753]
    goal:
      - [[4.14, 20.81, 0.753], [18.8, 18.78, -2.266], [20.02, 32.17, 2.282]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [0.5, 20.73, 2.027]
    goal:
      - [[0.5, 20.73, 2.027], [20.56, 19.47, -1.563], [19.24, 38.8, -1.715]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [1.83, 18.88, 1.896]
    goal:
      - [[1.83, 18.88, 1.896], [20.94, 21.33, -0.913], [19.4, 30.42, -0.701]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.33, 20.76, 0.632]
    goal:
      - [[11.33, 20.76, 0.632], [19.67, 18.79, -2.836], [20.76, 38.93, -2.134]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.33, 20.8, 2.71]
    goal:
      - [[14.33, 20.8, 2.71], [19.67, 19.09, -2.648], [20.31, 33.62, -1.351]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [3.02, 19.82, 0.377]
    goal:
      - [[3.02, 19.82, 0.377], [19.8, 20.66, 2.314], [20.79, 4.0, -1.746]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [34.6, 20.22, -0.237]
    goal:
      - [[34.6, 20.22, -0.237], [18.65, 20.58, -2.288], [20.7, 35.13, -0.326]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [26.7, 19.01, 1.999]
    goal:
      - [[26.7, 19.01, 1.999], [19.68, 19.94, 1.593], [19.35, 4.38, 2.214]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [37.11, 21.12, -0.426]
    goal:
      - [[37.11, 21.12, -0.426], [18.78, 19.25, 0.61], [19.49, 13.66, -1.823]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [36.19, 19.3, 0.983]
    goal:
      - [[36.19, 19.3, 0.983], [19.66, 20.15, 2.231], [20.73, 5.48, 0.721]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
