world:
  height: 40.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [8.0, 21.3, 0.0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.0, 20.0, 0.0]
    goal: [38.5, 20.0, 0.0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [8.8, 31.2, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [8.8, 8.8, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [31.2, 8.8, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.6, width: 17.6}
    state: [31.2, 31.2, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.59, 0.99, -2.32]
    goal:
      - [[19.59, 0.99, -2.32], [19.95, 28.46, -1.514]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [3.98, 20.73, -2.178]
    goal:
      - [[3.98, 20.73, -2.178], [36.04, 21.11, -0.903]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.13, 20.52, -0.262]
    goal:
      - [[14.13, 20.52, -0.262], [27.25, 18.99, -1.182]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [26.36, 19.02, 2.997]
    goal:
      - [[26.36, 19.02, 2.997], [5.19, 18.99, 0.161]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [37.08, 20.57, -0.674]
    goal:
      - [[37.08, 20.57, -0.674], [2.19, 20.0, 1.008]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [21.2, 39.36, -2.304]
    goal:
      - [[21.2, 39.36, -2.304], [19.86, 20.87, -3.038], [27.5, 20.75, -1.74]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.88, 28.22, -3.072]
    goal:
      - [[19.88, 28.22, -3.072], [20.55, 19.5, -2.35], [29.47, 19.93, -2.425]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [4.23, 18.73, -0.61]
    goal:
      - [[4.23, 18.73, -0.61], [19.34, 21.17, 2.298], [20.46, 34.75, 2.151]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.15, 19.21, 0.764]
    goal:
      - [[14.15, 19.21, 0.764], [21.4, 19.24, -0.154], [19.06, 35.0, -0.193]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [2.01, 19.85, 0.241]
    goal:
      - [[2.01, 19.85, 0.241], [21.28, 18.88, -0.125], [20.35, 11.82, 2.887]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
