world:
  height: 40.0
  width: 40.0
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: False}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [8.0, 21.3, 0.0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.0, 20.0, 0.0]
    goal: [38.5, 20.0, 0.0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }

obstacle:
  - shape: {name: rectangle, length: 17.3, width: 17.3}
    state: [8.65, 31.35, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.3, width: 17.3}
    state: [8.65, 8.65, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.3, width: 17.3}
    state: [31.35, 8.65, 0]
    color: darkgray
  - shape: {name: rectangle, length: 17.3, width: 17.3}
    state: [31.35, 31.35, 0]
    color: darkgray

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.74, 3.67, -1.447]
    goal:
      - [[20.74, 3.67, -1.447], [19.17, 33.81, -1.831]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.05, 7.33, -2.937]
    goal:
      - [[20.05, 7.33, -2.937], [18.79, 35.07, -0.265]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.23, 11.65, -2.565]
    goal:
      - [[19.23, 11.65, -2.565], [20.85, 28.4, 0.43]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [0.77, 19.67, 1.276]
    goal:
      - [[0.77, 19.67, 1.276], [28.53, 19.63, 1.615]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [35.79, 18.88, -1.36]
    goal:
      - [[35.79, 18.88, -1.36], [12.05, 20.04, 1.474]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [33.39, 20.36, 0.113]
    goal:
      - [[33.39, 20.36, 0.113], [13.19, 18.9, -0.697]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.96, 26.31, 1.272]
    goal:
      - [[18.96, 26.31, 1.272], [18.4, 20.53, 0.253], [11.92, 20.64, 3.025]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.85, 28.24, -1.142]
    goal:
      - [[19.85, 28.24, -1.142], [20.05, 21.46, 0.997], [4.93, 20.37, 1.516]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [21.52, 10.06, -0.684]
    goal:
      - [[21.52, 10.06, -0.684], [19.59, 20.84, 2.493], [30.74, 19.02, 0.932]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.56, 5.19, -0.664]
    goal:
      - [[20.56, 5.19, -0.664], [19.69, 19.37, 2.383], [34.3, 19.54, -3.069]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.7, 3.06, -1.065]
    goal:
      - [[18.7, 3.06, -1.065], [19.27, 19.01, 0.874], [13.64, 19.15, -3.112]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.64, 1.52, -0.606]
    goal:
      - [[19.64, 1.52, -0.606], [19.81, 20.34, -0.91], [13.85, 19.25, 3.133]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.58, 5.3, -3.106]
    goal:
      - [[18.58, 5.3, -3.106], [20.98, 21.51, 1.237], [3.77, 18.87, 1.361]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.97, 14.13, 1.215]
    goal:
      - [[18.97, 14.13, 1.215], [20.54, 18.99, -1.928], [5.64, 18.41, 1.548]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [2.81, 21.36, -1.892]
    goal:
      - [[2.81, 21.36, -1.892], [18.78, 19.63, -0.305], [20.34, 12.38, 2.226]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [25.8, 19.37, -2.646]
    goal:
      - [[25.8, 19.37, -2.646], [20.74, 19.96, 1.903], [18.58, 6.69, 1.142]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [34.66, 20.55, 1.315]
    goal:
      - [[34.66, 20.55, 1.315], [18.8, 18.3, 0.523], [21.02, 0.69, -0.631]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [28.17, 21.54, -2.65]
    goal:
      - [[28.17, 21.54, -2.65], [18.58, 19.77, 2.961], [21.08, 1.88, 2.857]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.4
    }
