world:
  height: 30
  width: 30
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: false}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [3.5, 15, 0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [5, 15, 0]
    goal: [28, 15, 0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: true
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: true
      show_goal: false
      show_trail: true
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.27, 7.1, 1.73]
    goal:
      - [[16.27, 7.1, 1.73], [13.73, 22.9, -1.412]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [9.64, 20.94, -0.836]
    goal:
      - [[9.64, 20.94, -0.836], [20.36, 9.06, 2.306]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.97, 14.27, 3.05]
    goal:
      - [[22.97, 14.27, 3.05], [7.03, 15.73, -0.091]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.13, 13.58, 0.178]
    goal:
      - [[7.13, 13.58, 0.178], [22.87, 16.42, -2.964]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.39, 19.51, -0.599]
    goal:
      - [[8.39, 19.51, -0.599], [21.61, 10.49, 2.543]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [21.92, 10.99, 2.617]
    goal:
      - [[21.92, 10.99, 2.617], [8.08, 19.01, -0.525]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.28, 22.08, -1.088]
    goal:
      - [[11.28, 22.08, -1.088], [18.72, 7.92, 2.054]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.02, 7.58, 1.189]
    goal:
      - [[12.02, 7.58, 1.189], [17.98, 22.42, -1.952]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.84, 7.08, 1.426]
    goal:
      - [[13.84, 7.08, 1.426], [16.16, 22.92, -1.716]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.9, 11.31, 0.48]
    goal:
      - [[7.9, 11.31, 0.48], [22.1, 18.69, -2.662]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.8, 21.4, -2.214]
    goal:
      - [[19.8, 21.4, -2.214], [10.2, 8.6, 0.928]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.98, 22.94, -1.443]
    goal:
      - [[13.98, 22.94, -1.443], [16.02, 7.06, 1.698]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.61, 22.14, -2.039]
    goal:
      - [[18.61, 22.14, -2.039], [11.39, 7.86, 1.103]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.38, 18.09, -2.745]
    goal:
      - [[22.38, 18.09, -2.745], [7.62, 11.91, 0.396]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [21.55, 19.59, -2.53]
    goal:
      - [[21.55, 19.59, -2.53], [8.45, 10.41, 0.611]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.91, 16.21, -2.989]
    goal:
      - [[22.91, 16.21, -2.989], [7.09, 13.79, 0.152]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.64, 9.32, 2.353]
    goal:
      - [[20.64, 9.32, 2.353], [9.36, 20.68, -0.789]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.18, 16.67, -0.21]
    goal:
      - [[7.18, 16.67, -0.21], [22.82, 13.33, 2.931]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.85, 9.89, 0.693]
    goal:
      - [[8.85, 9.89, 0.693], [21.15, 20.11, -2.449]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.35, 8.29, 2.146]
    goal:
      - [[19.35, 8.29, 2.146], [10.65, 21.71, -0.995]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [10.42, 8.44, 0.962]
    goal:
      - [[10.42, 8.44, 0.962], [19.58, 21.56, -2.18]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.5, 22.86, -1.759]
    goal:
      - [[16.5, 22.86, -1.759], [13.5, 7.14, 1.383]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.49, 12.19, 2.783]
    goal:
      - [[22.49, 12.19, 2.783], [7.51, 17.81, -0.358]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.73, 22.67, -1.283]
    goal:
      - [[12.73, 22.67, -1.283], [17.27, 7.33, 1.858]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.0, 15.2, -0.025]
    goal:
      - [[7.0, 15.2, -0.025], [23.0, 14.8, 3.117]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
