world:
  height: 30
  width: 30
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: false}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [8, 16.5, 0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8, 15, 0]
    goal: [28, 15, 0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: true
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: true
      show_goal: false
      show_trail: true
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7.0,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.45, 13.96, -0.543]
    goal:
      - [[18.45, 13.96, -0.543], [12.02, 11.89, 1.051]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.65, 19.05, 0.261]
    goal:
      - [[15.65, 19.05, 0.261], [13.47, 14.95, 1.1]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.61, 13.07, -0.634]
    goal:
      - [[13.61, 13.07, -0.634], [17.32, 13.39, 2.357]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.05, 11.26, -0.533]
    goal:
      - [[16.05, 11.26, -0.533], [12.48, 16.23, 1.435]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.71, 17.54, 1.145]
    goal:
      - [[11.71, 17.54, 1.145], [16.98, 14.67, -2.065]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.57, 11.98, -3.129]
    goal:
      - [[17.57, 11.98, -3.129], [12.99, 12.69, 2.749]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.3, 15.38, -0.35]
    goal:
      - [[17.3, 15.38, -0.35], [16.28, 16.05, 3.074]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.81, 13.77, -2.33]
    goal:
      - [[14.81, 13.77, -2.33], [11.2, 16.02, -1.498]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.9, 14.23, -1.136]
    goal:
      - [[16.9, 14.23, -1.136], [18.65, 14.21, 0.088]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.27, 16.8, -0.101]
    goal:
      - [[15.27, 16.8, -0.101], [18.29, 19.35, -0.844]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.34, 10.79, 0.986]
    goal:
      - [[12.34, 10.79, 0.986], [16.72, 18.13, 0.795]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.21, 18.58, -0.036]
    goal:
      - [[14.21, 18.58, -0.036], [19.39, 16.76, -0.962]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.63, 11.99, 1.382]
    goal:
      - [[12.63, 11.99, 1.382], [14.27, 17.6, -0.697]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.05, 11.69, -0.939]
    goal:
      - [[19.05, 11.69, -0.939], [13.33, 19.39, -0.156]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.24, 12.66, 0.105]
    goal:
      - [[16.24, 12.66, 0.105], [11.98, 14.57, -2.471]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.7, 18.17, 1.25]
    goal:
      - [[16.7, 18.17, 1.25], [12.03, 18.3, 2.207]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.07, 15.16, -2.588]
    goal:
      - [[14.07, 15.16, -2.588], [14.33, 11.61, -1.128]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.88, 19.39, -2.212]
    goal:
      - [[11.88, 19.39, -2.212], [11.18, 12.75, 1.399]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.56, 16.26, -2.748]
    goal:
      - [[18.56, 16.26, -2.748], [18.91, 12.6, -0.946]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.76, 18.57, -0.331]
    goal:
      - [[12.76, 18.57, -0.331], [15.32, 14.75, -1.522]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.81, 10.6, 1.323]
    goal:
      - [[17.81, 10.6, 1.323], [15.34, 12.82, 1.108]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.48, 14.8, 0.93]
    goal:
      - [[12.48, 14.8, 0.93], [17.6, 16.44, 0.693]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.09, 18.05, -2.654]
    goal:
      - [[19.09, 18.05, -2.654], [15.32, 17.0, 1.023]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.16, 14.99, 2.198]
    goal:
      - [[19.16, 14.99, 2.198], [13.21, 10.92, 0.128]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.03, 10.77, 1.417]
    goal:
      - [[11.03, 10.77, 1.417], [15.3, 18.59, -1.251]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
