world:
  height: 30
  width: 30
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: false}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [6.5, 15, 0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8, 15, 0]
    goal: [28, 15, 0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: true
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: true
      show_goal: false
      show_trail: true
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7.0,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.23, 18.28, -0.715]
    goal:
      - [[11.23, 18.28, -0.715], [18.77, 11.72, 2.426]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.19, 10.5, 2.024]
    goal:
      - [[17.19, 10.5, 2.024], [12.81, 19.5, -1.118]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.26, 11.68, 0.726]
    goal:
      - [[11.26, 11.68, 0.726], [18.74, 18.32, -2.416]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.69, 16.74, -2.786]
    goal:
      - [[19.69, 16.74, -2.786], [10.31, 13.26, 0.355]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.69, 19.95, -1.709]
    goal:
      - [[15.69, 19.95, -1.709], [14.31, 10.05, 1.433]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.73, 19.46, -1.1]
    goal:
      - [[12.73, 19.46, -1.1], [17.27, 10.54, 2.041]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.0, 14.85, 3.111]
    goal:
      - [[20.0, 14.85, 3.111], [10.0, 15.15, -0.03]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.4, 11.33, 2.317]
    goal:
      - [[18.4, 11.33, 2.317], [11.6, 18.67, -0.824]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [10.28, 13.36, 0.335]
    goal:
      - [[10.28, 13.36, 0.335], [19.72, 16.64, -2.807]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.99, 18.01, -2.496]
    goal:
      - [[18.99, 18.01, -2.496], [11.01, 11.99, 0.646]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
