world:
  height: 30
  width: 30
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: false}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [8, 16.5, 0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8, 15, 0]
    goal: [28, 15, 0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: true
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: true
      show_goal: false
      show_trail: true
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7.0,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.13, 13.74, -0.004]
    goal:
      - [[12.13, 13.74, -0.004], [12.13, 18.61, 1.44]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.03, 11.11, 0.005]
    goal:
      - [[14.03, 11.11, 0.005], [14.03, 18.65, -0.005]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.73, 12.42, -0.265]
    goal:
      - [[16.73, 12.42, -0.265], [16.73, 15.18, -0.925]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.12, 15.15, 3.028]
    goal:
      - [[19.12, 15.15, 3.028], [19.12, 12.74, -0.869]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.5, 12.97, 2.72]
    goal:
      - [[19.5, 12.97, 2.72], [19.5, 16.98, -2.465]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.02, 15.54, 0.715]
    goal:
      - [[13.02, 15.54, 0.715], [13.02, 12.86, -2.181]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [10.59, 11.49, 2.9]
    goal:
      - [[10.59, 11.49, 2.9], [10.59, 15.9, 2.385]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.5, 18.47, -3.016]
    goal:
      - [[15.5, 18.47, -3.016], [15.5, 17.31, 0.083]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.04, 12.42, -1.586]
    goal:
      - [[18.04, 12.42, -1.586], [18.04, 16.81, 0.319]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.99, 19.99, 1.87]
    goal:
      - [[19.99, 19.99, 1.87], [19.99, 16.78, 0.841]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.09, 16.32, 0.25]
    goal:
      - [[14.09, 16.32, 0.25], [14.09, 12.19, 2.603]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.49, 17.01, 2.316]
    goal:
      - [[11.49, 17.01, 2.316], [11.49, 15.47, 0.888]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.35, 12.5, -1.911]
    goal:
      - [[14.35, 12.5, -1.911], [14.35, 15.43, 3.01]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.25, 11.12, -1.663]
    goal:
      - [[15.25, 11.12, -1.663], [15.25, 19.19, 2.3]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.87, 18.68, 0.841]
    goal:
      - [[19.87, 18.68, 0.841], [19.87, 11.82, -0.016]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [10.23, 15.89, -1.792]
    goal:
      - [[10.23, 15.89, -1.792], [10.23, 11.73, 0.285]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.89, 18.32, 0.057]
    goal:
      - [[16.89, 18.32, 0.057], [16.89, 15.66, -2.556]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.55, 11.74, 0.497]
    goal:
      - [[19.55, 11.74, 0.497], [19.55, 18.87, -1.9]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.03, 16.87, 2.529]
    goal:
      - [[18.03, 16.87, 2.529], [18.03, 14.16, -1.762]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.52, 14.91, 1.269]
    goal:
      - [[17.52, 14.91, 1.269], [17.52, 16.32, 0.43]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.09, 17.02, 0.631]
    goal:
      - [[15.09, 17.02, 0.631], [15.09, 11.6, 1.145]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.39, 14.13, 1.535]
    goal:
      - [[13.39, 14.13, 1.535], [13.39, 16.71, 2.322]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.66, 16.43, 2.49]
    goal:
      - [[19.66, 16.43, 2.49], [19.66, 10.17, 3.125]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.79, 10.19, 1.084]
    goal:
      - [[19.79, 10.19, 1.084], [19.79, 12.72, 1.428]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.72, 13.98, -1.842]
    goal:
      - [[15.72, 13.98, -1.842], [15.72, 18.17, -0.414]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
