world:
  height: 30
  width: 30
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: false}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [5, 16.5, 0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [5, 15, 0]
    goal: [28, 15, 0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: true
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: true
      show_goal: false
      show_trail: true
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7.0,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.61, 22.25, -1.133]
    goal:
      - [[11.61, 22.25, -1.133], [18.39, 7.75, 2.008]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.69, 21.48, -2.197]
    goal:
      - [[19.69, 21.48, -2.197], [10.31, 8.52, 0.945]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.11, 16.34, -0.168]
    goal:
      - [[7.11, 16.34, -0.168], [22.89, 13.66, 2.974]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.9, 7.0, 1.558]
    goal:
      - [[14.9, 7.0, 1.558], [15.1, 23.0, -1.583]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.64, 18.13, -0.402]
    goal:
      - [[7.64, 18.13, -0.402], [22.36, 11.87, 2.74]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.91, 13.83, 2.995]
    goal:
      - [[22.91, 13.83, 2.995], [7.09, 16.17, -0.147]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.31, 22.82, -1.358]
    goal:
      - [[13.31, 22.82, -1.358], [16.69, 7.18, 1.783]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.63, 17.41, -2.836]
    goal:
      - [[22.63, 17.41, -2.836], [7.37, 12.59, 0.306]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [21.32, 10.1, 2.482]
    goal:
      - [[21.32, 10.1, 2.482], [8.68, 19.9, -0.66]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.77, 7.2, 1.794]
    goal:
      - [[16.77, 7.2, 1.794], [13.23, 22.8, -1.347]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.09, 7.62, 1.967]
    goal:
      - [[18.09, 7.62, 1.967], [11.91, 22.38, -1.174]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.62, 20.7, -2.349]
    goal:
      - [[20.62, 20.7, -2.349], [9.38, 9.3, 0.792]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [9.78, 21.07, -0.861]
    goal:
      - [[9.78, 21.07, -0.861], [20.22, 8.93, 2.281]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.32, 19.4, -0.583]
    goal:
      - [[8.32, 19.4, -0.583], [21.68, 10.6, 2.559]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [22.09, 18.71, -2.66]
    goal:
      - [[22.09, 18.71, -2.66], [7.91, 11.29, 0.482]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.69, 7.11, 1.406]
    goal:
      - [[13.69, 7.11, 1.406], [16.31, 22.89, -1.736]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8.67, 10.11, 0.657]
    goal:
      - [[8.67, 10.11, 0.657], [21.33, 19.89, -2.485]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.05, 14.08, 0.115]
    goal:
      - [[7.05, 14.08, 0.115], [22.95, 15.92, -3.027]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.55, 8.42, 2.175]
    goal:
      - [[19.55, 8.42, 2.175], [10.45, 21.58, -0.967]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [9.77, 8.95, 0.858]
    goal:
      - [[9.77, 8.95, 0.858], [20.23, 21.05, -2.284]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.66, 22.99, -1.528]
    goal:
      - [[14.66, 22.99, -1.528], [15.34, 7.01, 1.614]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.52, 7.8, 1.12]
    goal:
      - [[11.52, 7.8, 1.12], [18.48, 22.2, -2.021]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.77, 22.5, -1.925]
    goal:
      - [[17.77, 22.5, -1.925], [12.23, 7.5, 1.217]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.35, 12.67, 0.295]
    goal:
      - [[7.35, 12.67, 0.295], [22.65, 17.33, -2.846]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [7.87, 11.37, 0.471]
    goal:
      - [[7.87, 11.37, 0.471], [22.13, 18.63, -2.671]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
