world:
  height: 30
  width: 30
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: false}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [8, 16.5, 0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8, 15, 0]
    goal: [28, 15, 0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: true
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: true
      show_goal: false
      show_trail: true
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7.0,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.48, 19.61, -1.925]
    goal:
      - [[15.48, 19.61, -1.925], [15.48, 12.11, -3.009]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.11, 19.53, 0.21]
    goal:
      - [[17.11, 19.53, 0.21], [17.11, 10.09, 2.642]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.19, 12.69, -2.03]
    goal:
      - [[19.19, 12.69, -2.03], [19.19, 13.72, -1.772]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.93, 16.79, -2.795]
    goal:
      - [[14.93, 16.79, -2.795], [14.93, 15.36, 2.464]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.57, 11.84, -2.52]
    goal:
      - [[16.57, 11.84, -2.52], [16.57, 15.39, 0.035]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.99, 12.86, -2.762]
    goal:
      - [[11.99, 12.86, -2.762], [11.99, 17.96, -0.662]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.72, 10.19, 0.572]
    goal:
      - [[13.72, 10.19, 0.572], [13.72, 14.5, -1.268]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.49, 12.61, -1.147]
    goal:
      - [[17.49, 12.61, -1.147], [17.49, 17.05, -1.238]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.72, 15.81, 0.545]
    goal:
      - [[16.72, 15.81, 0.545], [16.72, 13.76, 0.724]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.79, 17.22, 2.46]
    goal:
      - [[11.79, 17.22, 2.46], [11.79, 13.21, -2.419]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.85, 15.09, 0.821]
    goal:
      - [[17.85, 15.09, 0.821], [17.85, 10.19, 0.281]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.43, 19.23, 1.459]
    goal:
      - [[19.43, 19.23, 1.459], [19.43, 14.39, -2.693]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.08, 13.04, -2.359]
    goal:
      - [[14.08, 13.04, -2.359], [14.08, 15.11, 0.73]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [17.45, 18.08, 1.82]
    goal:
      - [[17.45, 18.08, 1.82], [17.45, 15.54, 0.707]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.65, 10.82, 1.832]
    goal:
      - [[12.65, 10.82, 1.832], [12.65, 16.61, -1.046]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.05, 10.83, -2.547]
    goal:
      - [[19.05, 10.83, -2.547], [19.05, 12.01, 2.899]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.46, 14.86, -2.904]
    goal:
      - [[12.46, 14.86, -2.904], [12.46, 18.35, 2.3]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.81, 13.83, 0.653]
    goal:
      - [[19.81, 13.83, 0.653], [19.81, 19.63, -0.905]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.5, 16.33, 0.034]
    goal:
      - [[13.5, 16.33, 0.034], [13.5, 12.85, -2.997]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.96, 10.65, 1.93]
    goal:
      - [[16.96, 10.65, 1.93], [16.96, 17.75, 1.509]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "sfm",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      gain_k: 1.5,
      gain_a_static: 5.0,
      gain_b_static: 0.25,
      gain_a_agent: 7,
      gain_b_agent: 0.3,
      avoid_dis: 5.0,
      safe_dist: 0.5
    }
