world:
  height: 30
  width: 30
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]
  collision_mode: unobstructed_obstacles
  control_mode: auto
  mdownsample: 2
  planner: {dialate: 10, skip_num: 5, smooth: false}

robot:
  - kinematics: {name: diff}
    shape: {name: rectangle, length: 0.7, width: 0.55, wheelbase: 0.5}
    state: [6.5, 15, 0]
    vel_min: [-2.0, -3.141592653589793]
    vel_max: [2.0, 3.141592653589793]
    acce: [2.0, 3.141592653589793]
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    sensors:
      - type: lidar2d
        range_min: 0
        range_max: 5
        angle_range: 6.283185307179586
        number: 200
        noise: False
        alpha: 0.3
        build_map: True
        map_resolution: 0.1

target:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [8, 15, 0]
    goal: [28, 15, 0]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: true
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: true
      show_goal: false
      show_trail: true
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }

eval:
  init_recorder: True

human:
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.43, 18.06, -0.607]
    goal:
      - [[13.43, 18.06, -0.607], [13.43, 13.57, 2.821]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.06, 15.59, -1.35]
    goal:
      - [[15.06, 15.59, -1.35], [15.06, 14.4, -1.989]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [20.0, 16.08, -0.202]
    goal:
      - [[20.0, 16.08, -0.202], [20.0, 12.5, -0.378]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.6, 16.11, 2.383]
    goal:
      - [[16.6, 16.11, 2.383], [16.6, 13.72, 0.392]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.99, 12.01, 3.128]
    goal:
      - [[14.99, 12.01, 3.128], [14.99, 17.62, 2.415]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.05, 10.07, 1.478]
    goal:
      - [[14.05, 10.07, 1.478], [14.05, 17.48, 1.993]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.73, 10.79, 1.55]
    goal:
      - [[15.73, 10.79, 1.55], [15.73, 15.26, 0.962]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [10.3, 19.39, -2.971]
    goal:
      - [[10.3, 19.39, -2.971], [10.3, 14.62, -0.465]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.33, 19.43, 1.798]
    goal:
      - [[18.33, 19.43, 1.798], [18.33, 11.9, -0.783]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.32, 14.8, 0.942]
    goal:
      - [[11.32, 14.8, 0.942], [11.32, 19.76, 1.129]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.85, 19.45, 1.413]
    goal:
      - [[14.85, 19.45, 1.413], [14.85, 16.01, -1.092]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.45, 16.05, 0.661]
    goal:
      - [[11.45, 16.05, 0.661], [11.45, 13.01, 1.995]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.98, 12.92, 0.469]
    goal:
      - [[16.98, 12.92, 0.469], [16.98, 18.19, -2.124]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.27, 19.65, 2.64]
    goal:
      - [[13.27, 19.65, 2.64], [13.27, 17.97, 0.59]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.42, 12.51, -1.542]
    goal:
      - [[11.42, 12.51, -1.542], [11.42, 15.69, 1.335]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [16.37, 17.31, -2.397]
    goal:
      - [[16.37, 17.31, -2.397], [16.37, 14.78, 2.543]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.26, 13.93, -2.224]
    goal:
      - [[19.26, 13.93, -2.224], [19.26, 17.85, 0.592]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.26, 10.88, 2.265]
    goal:
      - [[19.26, 10.88, 2.265], [19.26, 12.59, 1.363]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [10.23, 15.38, 2.384]
    goal:
      - [[10.23, 15.38, 2.384], [10.23, 10.46, -2.37]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [10.61, 10.46, 2.508]
    goal:
      - [[10.61, 10.46, 2.508], [10.61, 17.7, 0.0]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [13.99, 16.25, 1.266]
    goal:
      - [[13.99, 16.25, 1.266], [13.99, 12.66, 0.658]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [11.85, 20.0, -3.091]
    goal:
      - [[11.85, 20.0, -3.091], [11.85, 13.2, 0.863]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [15.5, 14.41, -0.748]
    goal:
      - [[15.5, 14.41, -0.748], [15.5, 18.74, -0.792]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.46, 12.46, -1.375]
    goal:
      - [[19.46, 12.46, -1.375], [19.46, 16.75, 0.948]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.68, 17.6, 0.637]
    goal:
      - [[14.68, 17.6, 0.637], [14.68, 15.57, -0.139]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [12.67, 11.41, -0.83]
    goal:
      - [[12.67, 11.41, -0.83], [12.67, 18.32, -3.036]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [18.69, 16.11, -0.495]
    goal:
      - [[18.69, 16.11, -0.495], [18.69, 15.02, 0.209]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.72, 13.22, 1.697]
    goal:
      - [[14.72, 13.22, 1.697], [14.72, 17.53, 2.903]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [19.93, 19.7, -0.992]
    goal:
      - [[19.93, 19.7, -0.992], [19.93, 18.28, -3.023]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
  - kinematics: {name: omni}
    shape: {name: circle, radius: 0.3}
    state: [14.18, 14.41, 1.598]
    goal:
      - [[14.18, 14.41, 1.598], [14.18, 17.99, -2.113]]
    vel_min: [-1.5, -1.5]
    vel_max: [1.5, 1.5]
    plan_path: True
    goal_threshold: 2.0
    state_dim: 3
    plot:
      show_trajectory: True
      show_goal: False
      show_trail: True
      keep_trail_length: 10
      keep_traj_length: 10
    behavior: {
      name: "orca",
      vxmax: 1.5,
      vymax: 1.5,
      acceler: 1.0,
      safe_dist: 0.5
    }
